// import '';

class Autogenerated {
  int? status;
  String? message;
  Data? data;

  Autogenerated({this.status, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  User? user;
  String? token;

  Data({this.user, this.token});

  Data.fromJson(Map<String, dynamic> json) {
    user = json['user'] != null ? new User.fromJson(json['user']) : null;
    token = json['token'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    data['token'] = this.token;
    return data;
  }
}

class User {
  int? id;
  String? profileName;
  String? profileImage;
  String? email;
  int? phone;
  String? emailVerifiedAt;
  String? deviceToken;
  int? isActive;
  int? otp;
  String? gender;
  String? socialLoginProvider;
  String? socialLoginToken;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  User(
      {this.id,
      this.profileName,
      this.profileImage,
      this.email,
      this.phone,
      this.emailVerifiedAt,
      this.deviceToken,
      this.isActive,
      this.otp,
      this.gender,
      this.socialLoginProvider,
      this.socialLoginToken,
      this.createdAt,
      this.updatedAt,
      this.deletedAt});

  User.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    profileName = json['profile_name'];
    profileImage = json['profile_image'];
    email = json['email'];
    phone = json['phone'];
    emailVerifiedAt = json['email_verified_at'];
    deviceToken = json['device_token'];
    isActive = json['is_active'];
    otp = json['otp'];
    gender = json['gender'];
    socialLoginProvider = json['social_login_provider'];
    socialLoginToken = json['social_login_token'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    deletedAt = json['deleted_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['profile_name'] = this.profileName;
    data['profile_image'] = this.profileImage;
    data['email'] = this.email;
    data['phone'] = this.phone;
    data['email_verified_at'] = this.emailVerifiedAt;
    data['device_token'] = this.deviceToken;
    data['is_active'] = this.isActive;
    data['otp'] = this.otp;
    data['gender'] = this.gender;
    data['social_login_provider'] = this.socialLoginProvider;
    data['social_login_token'] = this.socialLoginToken;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['deleted_at'] = this.deletedAt;
    return data;
  }
}
